package io.renren.modules.zd.entity;

import com.baomidou.mybatisplus.annotations.TableField;
import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.annotations.TableName;
import com.baomidou.mybatisplus.enums.FieldFill;
import com.baomidou.mybatisplus.enums.IdType;

import javax.validation.constraints.Min;
import java.math.BigDecimal;
import java.util.Date;
@TableName("zd_balance_pay")
public class ZdBalancePayEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_pay_resource.id
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    @TableId(value = "id_", type = IdType.UUID)
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_pay_resource.balance_no
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    private String balanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_pay_resource.low_level_org
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    private String lowLevelOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_pay_resource.sum
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    @Min(value = 1)
    private BigDecimal sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_pay_resource.operator
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    @TableField(fill = FieldFill.INSERT)
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_pay_resource.create_time
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    @TableField(fill = FieldFill.INSERT)
    private Date createTime;

    private BigDecimal shouldPay;
    
    private BigDecimal debt;
    
    
    public BigDecimal getShouldPay() {
		return shouldPay;
	}

	public void setShouldPay(BigDecimal shouldPay) {
		this.shouldPay = shouldPay;
	}

	public BigDecimal getDebt() {
		return debt;
	}

	public void setDebt(BigDecimal debt) {
		this.debt = debt;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_pay_resource.low_level_org
     *
     * @return the value of balance_pay_resource.low_level_org
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public String getLowLevelOrg() {
        return lowLevelOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_pay_resource.low_level_org
     *
     * @param lowLevelOrg the value for balance_pay_resource.low_level_org
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public void setLowLevelOrg(String lowLevelOrg) {
        this.lowLevelOrg = lowLevelOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_pay_resource.sum
     *
     * @return the value of balance_pay_resource.sum
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public BigDecimal getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_pay_resource.sum
     *
     * @param sum the value for balance_pay_resource.sum
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public void setSum(BigDecimal sum) {
        this.sum = sum;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_pay_resource.create_time
     *
     * @return the value of balance_pay_resource.create_time
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_pay_resource.create_time
     *
     * @param createTime the value for balance_pay_resource.create_time
     *
     * @mbggenerated Sat May 12 12:19:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getBalanceId() {
        return balanceId;
    }

    public void setBalanceId(String balanceId) {
        this.balanceId = balanceId;
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
}