package io.renren.modules.zd.entity;

import com.baomidou.mybatisplus.annotations.TableField;
import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.annotations.TableName;
import com.baomidou.mybatisplus.enums.FieldFill;
import com.baomidou.mybatisplus.enums.IdType;

import java.math.BigDecimal;
import java.util.Date;
@TableName("zd_balance")
public class ZdBalanceEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.id
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    @TableId(value = "id_", type = IdType.UUID)
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.balance_id
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
//    @TableId(value = "balance_id", type = IdType.UUID)
    private String balanceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.high_level_org
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private String highLevelOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.low_level_org
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private String lowLevelOrg;
    
    //结算单位中文
    @TableField(exist = false)
    private String lowLevelOrgName;

    
    public String getLowLevelOrgName() {
		return lowLevelOrgName;
	}

	public void setLowLevelOrgName(String lowLevelOrgName) {
		this.lowLevelOrgName = lowLevelOrgName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.semester_code
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private String semesterCode;
    @TableField(exist = false)
    private String semesterCodeName;
    
    
    public String getSemesterCodeName() {
		return semesterCodeName;
	}

	public void setSemesterCodeName(String semesterCodeName) {
		this.semesterCodeName = semesterCodeName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.discount_rate
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private Integer discountRate;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.publish_price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private BigDecimal publishPriceTotal;
    private BigDecimal publishPriceShiyang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.refund_price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private BigDecimal refundPriceTotal;
    private BigDecimal refundPriceShiyang;

    public BigDecimal getPublishPriceShiyang() {
        return publishPriceShiyang;
    }

    public void setPublishPriceShiyang(BigDecimal publishPriceShiyang) {
        this.publishPriceShiyang = publishPriceShiyang;
    }

    public BigDecimal getRefundPriceShiyang() {
        return refundPriceShiyang;
    }

    public void setRefundPriceShiyang(BigDecimal refundPriceShiyang) {
        this.refundPriceShiyang = refundPriceShiyang;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private BigDecimal priceTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.actual_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private BigDecimal actualTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.balance_status
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private Integer balanceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.audit_status
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    private Integer auditStatus;


	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.create_time
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    @TableField(fill = FieldFill.INSERT)
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_balance.update_time
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    @TableField(fill = FieldFill.UPDATE)
    private Date updateTime;
    @TableField(fill = FieldFill.INSERT)
    private String createBy;
    @TableField(fill = FieldFill.UPDATE)
    private String updateBy;
    private String remark;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public String getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public String getBalanceNo() {
        return balanceNo;
    }

    public void setBalanceNo(String balanceNo) {
        this.balanceNo = balanceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.high_level_org
     *
     * @return the value of zd_balance.high_level_org
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public String getHighLevelOrg() {
        return highLevelOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.high_level_org
     *
     * @param highLevelOrg the value for zd_balance.high_level_org
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setHighLevelOrg(String highLevelOrg) {
        this.highLevelOrg = highLevelOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.low_level_org
     *
     * @return the value of zd_balance.low_level_org
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public String getLowLevelOrg() {
        return lowLevelOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.low_level_org
     *
     * @param lowLevelOrg the value for zd_balance.low_level_org
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setLowLevelOrg(String lowLevelOrg) {
        this.lowLevelOrg = lowLevelOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.semester_code
     *
     * @return the value of zd_balance.semester_code
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public String getSemesterCode() {
        return semesterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.semester_code
     *
     * @param semesterCode the value for zd_balance.semester_code
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setSemesterCode(String semesterCode) {
        this.semesterCode = semesterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.discount_rate
     *
     * @return the value of zd_balance.discount_rate
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public Integer getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.discount_rate
     *
     * @param discountRate the value for zd_balance.discount_rate
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setDiscountRate(Integer discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.publish_price_total
     *
     * @return the value of zd_balance.publish_price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public BigDecimal getPublishPriceTotal() {
        return publishPriceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.publish_price_total
     *
     * @param publishPriceTotal the value for zd_balance.publish_price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setPublishPriceTotal(BigDecimal publishPriceTotal) {
        this.publishPriceTotal = publishPriceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.refund_price_total
     *
     * @return the value of zd_balance.refund_price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public BigDecimal getRefundPriceTotal() {
        return refundPriceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.refund_price_total
     *
     * @param refundPriceTotal the value for zd_balance.refund_price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setRefundPriceTotal(BigDecimal refundPriceTotal) {
        this.refundPriceTotal = refundPriceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.price_total
     *
     * @return the value of zd_balance.price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public BigDecimal getPriceTotal() {
        return priceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.price_total
     *
     * @param priceTotal the value for zd_balance.price_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setPriceTotal(BigDecimal priceTotal) {
        this.priceTotal = priceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.actual_total
     *
     * @return the value of zd_balance.actual_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public BigDecimal getActualTotal() {
        return actualTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.actual_total
     *
     * @param actualTotal the value for zd_balance.actual_total
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setActualTotal(BigDecimal actualTotal) {
        this.actualTotal = actualTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.balance_status
     *
     * @return the value of zd_balance.balance_status
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public Integer getBalanceStatus() {
        return balanceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.balance_status
     *
     * @param balanceStatus the value for zd_balance.balance_status
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setBalanceStatus(Integer balanceStatus) {
        this.balanceStatus = balanceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.audit_status
     *
     * @return the value of zd_balance.audit_status
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.audit_status
     *
     * @param auditStatus the value for zd_balance.audit_status
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.create_time
     *
     * @return the value of zd_balance.create_time
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.create_time
     *
     * @param createTime the value for zd_balance.create_time
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_balance.update_time
     *
     * @return the value of zd_balance.update_time
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_balance.update_time
     *
     * @param updateTime the value for zd_balance.update_time
     *
     * @mbggenerated Tue May 08 23:31:42 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}